parallel_wavegan/bin/train.py
Fix additional memory consuming in the evaluation.
=> Add torch.no_grad() in evaluation

egs/arctic/voc1/conf/parallel_wavegan.v1.yaml, egs/csmsc/voc1/conf/parallel_wavegan.v1.yaml, egs/jsut/voc1/conf/parallel_wavegan.v1.yaml, egs/ljspeech/voc1/conf/parallel_wavegan.v1.yaml, egs/ljspeech/voc1/conf/parallel_wavegan.v2.yaml, parallel_wavegan/bin/train.py, parallel_wavegan/datasets/audio_mel_dataset.py, setup.py
This PR enables us to allow cache in the dataset.
This will help to increase the utilization of GPU by solving the load bottleneck.
=> Added cache option in Dataset

.github/workflows/ci.yaml, parallel_wavegan/bin/train.py
It's a boilerplate implementation of Distributed Data-Parallel training. 
for torch dsitributed:
```
CUDA_VISIBLE_DEVICES="0, 1" python  -m torch.distributed.launch --nproc_per_node=2  parallel_wavegan/bin/train.py --train-dumpdir egs/ljspeech/voc1/dump/train_nodev/norm --dev-dumpdir egs/ljspeech/voc1/dump/dev/norm --outdir ../keep --config egs/ljspeech/voc1/conf/parallel_wavegan.v1.yaml
```
for apex:
```
CUDA_VISIBLE_DEVICES="1,2,3,4,5,6,7" python3 -m apex.parallel.multiproc parallel_wavegan/bin/train.py ...
```
I lately tried 8 GPUs and experienced a speed up in convergence time with 4x higher learning rates. So it might be useful for other people.
=> DDP training with torch or apex.

.gitignore, README.md, egs/arctic/voc1/run.sh, egs/csmsc/voc1/run.sh, egs/jsut/voc1/run.sh, egs/ljspeech/voc1/run.sh, parallel_wavegan/bin/train.py, parallel_wavegan/distributed/launch.py, setup.py
- I found that `torch.nn.parallel.DistributedDataParallel` does not work well.
So I decided to keep only apex-based distributed data parallel #30.
- According to [apex example](https://github.com/NVIDIA/apex/blob/master/examples/simple/distributed/distributed_data_parallel.py), we do not need to specify world_size and other environmental variables. I simplified the code by removing unnecessary parts.
- Fixed the state_dict naming in the case of distributed training.
- Fixed never stopping training loop issue in non-zero rank processes.
- Update recipe to run the distributed training.
=> Fix distributed training and update recipes

parallel_wavegan/__init__.py, parallel_wavegan/bin/train.py, setup.py
- Removed unnecessary part in training code
- Fixed typos
=> Refactoring

README.md, egs/ljspeech/voc1/conf/parallel_wavegan.v1.long.yaml
Add 1000000 steps pretrained model.
=> Add 1000k steps pretrained model

egs/arctic/voc1/cmd.sh, egs/arctic/voc1/local/data_prep.sh, egs/arctic/voc1/path.sh, egs/arctic/voc1/run.sh, egs/csmsc/voc1/cmd.sh, egs/csmsc/voc1/local/data_prep.sh, egs/csmsc/voc1/path.sh, egs/csmsc/voc1/run.sh, egs/jsut/voc1/cmd.sh, egs/jsut/voc1/local/data_download.sh, egs/jsut/voc1/local/data_prep.sh, egs/jsut/voc1/path.sh, egs/jsut/voc1/run.sh, egs/ljspeech/voc1/cmd.sh, egs/ljspeech/voc1/local/data_download.sh, egs/ljspeech/voc1/local/data_prep.sh, egs/ljspeech/voc1/path.sh, egs/ljspeech/voc1/run.sh, parallel_wavegan/__init__.py, parallel_wavegan/bin/compute_statistics.py, parallel_wavegan/bin/decode.py, parallel_wavegan/bin/normalize.py, parallel_wavegan/bin/preprocess.py, parallel_wavegan/bin/train.py, parallel_wavegan/datasets/audio_mel_dataset.py, parallel_wavegan/utils/utils.py, setup.py
- Capitalize log
- Add more echo 
- Changed default cmd (stdout -> local)
I found that `stdout.pl` cannot stop when causing errors so I changed the default.
=> Clean scripts

README.md, egs/ljspeech/voc1/conf/parallel_wavegan.v1.no_limit.yaml
Add missing config `v1.no_limit.yaml`.
=> Add missing config

README.md, egs/arctic/voc1/run.sh, egs/csmsc/voc1/run.sh, egs/jsut/voc1/run.sh, egs/ljspeech/voc1/run.sh
=> Add comment in run.sh

egs/arctic/voc1/local/data_prep.sh, egs/csmsc/voc1/local/data_prep.sh, egs/jnas/voc1/local/data_prep.sh, egs/jsut/voc1/local/data_prep.sh, egs/ljspeech/voc1/local/data_prep.sh, utils/split_data.sh
- Introduce `utils/split_data.sh`
- Update `local/data_prep.sh` to use `split_data.sh`
- Too many duplicated lines
=> Update data prep scripts

README.md, egs/ljspeech/voc1/conf/melgan.v1.yaml
This PR adds the initial results of MelGAN generator config.
Training and decoding are very fast. The quality is slightly worse than PWG but maybe if we continue to train, the results become better. I will try the long iteration config.
Related to #46 #61
=> Add initial MelGAN config

README.md, parallel_wavegan/__init__.py, parallel_wavegan/bin/train.py, parallel_wavegan/models/melgan.py, setup.py, test/test_melgan.py
#46 #61 
This PR adds MelGAN's discriminator.
=> Add melgan discriminator

parallel_wavegan/bin/train.py, parallel_wavegan/models/melgan.py
=> Fix kernel size and fm loss normalization in MelGAN Discriminator

egs/ljspeech/voc1/conf/parallel_wavegan.v2.yaml, parallel_wavegan/models/parallel_wavegan.py
Add dilation_factor option to follow this comment. https://github.com/kan-bayashi/ParallelWaveGAN/issues/27#issuecomment-570816156
=> Support dilation factor in PWG discriminator

parallel_wavegan/__init__.py, parallel_wavegan/bin/train.py, setup.py
- Add `--pretrain` option to load only model parameters
=> Add --pretrain option

.github/workflows/ci.yaml, egs/arctic/voc1/run.sh, egs/csmsc/voc1/run.sh, egs/jnas/voc1/run.sh, egs/jsut/voc1/run.sh, egs/ljspeech/voc1/run.sh, egs/yesno/voc1/conf/parallel_wavegan.v1.debug.npy.yaml, egs/yesno/voc1/run.sh, parallel_wavegan/__init__.py, setup.py
=> Fix hard coding of "stats.h5" in the recipe

.github/workflows/ci.yaml, README.md
=> Add jq in  requirement 

egs/arctic/voc1/path.sh, egs/arctic/voc1/run.sh, egs/csmsc/voc1/path.sh, egs/csmsc/voc1/run.sh, egs/jnas/voc1/path.sh, egs/jnas/voc1/run.sh, egs/jsut/voc1/path.sh, egs/jsut/voc1/run.sh, egs/ljspeech/voc1/path.sh, egs/ljspeech/voc1/run.sh, egs/yesno/voc1/path.sh, egs/yesno/voc1/run.sh
=> Add installation check

egs/arctic/voc1/run.sh, egs/csmsc/voc1/run.sh, egs/jnas/voc1/run.sh, egs/jsut/voc1/run.sh, egs/ljspeech/voc1/run.sh, egs/vctk/voc1/run.sh, egs/yesno/voc1/run.sh, parallel_wavegan/__init__.py, parallel_wavegan/bin/normalize.py, parallel_wavegan/bin/preprocess.py, setup.py, utils/make_subset_data.sh, utils/split_scp.pl
Current parallel job in feature extraction is too slow.
This PR fixes this issue especially when we use large dataset.
=> New parallel job

parallel_wavegan/__init__.py, parallel_wavegan/bin/compute_statistics.py, parallel_wavegan/bin/decode.py, parallel_wavegan/bin/normalize.py, parallel_wavegan/bin/preprocess.py, parallel_wavegan/bin/train.py, parallel_wavegan/datasets/__init__.py, parallel_wavegan/datasets/audio_mel_dataset.py, parallel_wavegan/datasets/scp_dataset.py, setup.py
This PR allows using kaldi-style scp files for training.
From this version, you can easily integrate nerual vocoder training part in the espnet TTS recpes.
Related https://github.com/espnet/espnet/pull/1641
=> Support kaldi-style scp file in bin scripts

egs/vctk/voc1/conf/parallel_wavegan.v1.long.yaml, egs/vctk/voc1/conf/parallel_wavegan.v1.yaml, egs/vctk/voc1/local/data_download.sh, egs/vctk/voc1/local/data_prep.sh, egs/vctk/voc1/run.sh
=> Update VCTK recipe

parallel_wavegan/bin/decode.py, parallel_wavegan/bin/normalize.py, parallel_wavegan/bin/preprocess.py, parallel_wavegan/bin/train.py, utils/make_subset_data.sh
- `--allow-different-sampling-rate`
- `--skip-wav-copy`
=> Add new options

README.md
I will also add `parallel_wavegan.v1.long` model once I finished the training.
=> Add VCTK results

README.md, egs/ljspeech/voc1/conf/parallel_wavegan.v3.yaml
Add `parallel_wavegan.v3` config which uses PWG G + MelGAN D.
Related: #61
=> Add parallel_wavegan.v3 config and results

egs/arctic/voc1/local/data_prep.sh, egs/csmsc/voc1/local/data_prep.sh, egs/csmsc/voc1/path.sh, egs/jnas/voc1/local/data_prep.sh, egs/jsut/voc1/local/data_prep.sh, egs/ljspeech/voc1/local/data_prep.sh, egs/vctk/voc1/local/data_prep.sh, egs/yesno/voc1/local/data_prep.sh
- Add missing option and help message in `data_prep.sh`
- Add `nkf` installation check
- Add missing label check in csmsc recipe (Related to #105)
=> Minor update

egs/libritts/voc1/cmd.sh, egs/libritts/voc1/conf/parallel_wavegan.v1.long.yaml, egs/libritts/voc1/conf/parallel_wavegan.v1.yaml, egs/libritts/voc1/conf/slurm.conf, egs/libritts/voc1/local/data_download.sh, egs/libritts/voc1/local/data_prep.sh, egs/libritts/voc1/path.sh, egs/libritts/voc1/run.sh, parallel_wavegan/bin/decode.py
=> Add LibriTTS recipe

parallel_wavegan/__init__.py, parallel_wavegan/bin/train.py, setup.py
=> Change to re-compute fake y for discriminator update

README.md, egs/ljspeech/voc1/conf/multi_band_melgan.v2.yaml
This PR adds new multi-band melgan config which using Adam without a gradient norm.
Related #143
=> Add multi-band MelGAN v2 config

README.md, egs/jsut/voc1/conf/multi_band_melgan.v2.yaml
=> Add JSUT pretrained model with MB-MelGAN v2

egs/template_multi_spk/voc1/run.sh
=> Fix run.sh in multi_spk_template

parallel_wavegan/__init__.py, parallel_wavegan/datasets/scp_dataset.py, parallel_wavegan/utils/utils.py, setup.py
This PR enables to use feats.scp with npy format in ESPnet2.
=> Support npy scp loader

parallel_wavegan/bin/preprocess.py
=> Fix pad mode edge -> reflect 

parallel_wavegan/bin/train.py
=> Fix shuffle in distributed training

parallel_wavegan/losses/adversarial_loss.py, test/test_style_melgan.py
=> Support hinge loss in adversarial loss

parallel_wavegan/models/style_melgan.py
=> Prevent pop noise at the end of audio in StyleMelGAN inference

README.md, egs/yesno/voc1/conf/parallel_wavegan.v1.debug.npy.yaml, egs/yesno/voc1/run.sh, parallel_wavegan/__init__.py, parallel_wavegan/bin/decode.py, parallel_wavegan/bin/preprocess.py, parallel_wavegan/models/hifigan.py, parallel_wavegan/models/melgan.py, parallel_wavegan/models/parallel_wavegan.py, parallel_wavegan/models/style_melgan.py, parallel_wavegan/utils/utils.py, setup.py
- Support `normalize-before` to decode denormalized feature
- Support changing of `log_base` in preprocessing
=> Add useful functions

parallel_wavegan/bin/decode.py, parallel_wavegan/utils/utils.py
=> Change warn message in loading stats

egs/csmsc/voc1/conf/hifigan.v1.yaml, egs/jsut/voc1/conf/hifigan.v1.yaml, egs/libritts/voc1/conf/hifigan.v1.yaml, egs/ljspeech/voc1/conf/hifigan.v1.yaml, egs/vctk/voc1/conf/hifigan.v1.yaml, egs/yesno/voc1/conf/hifigan.v1.debug.yaml, parallel_wavegan/models/hifigan.py, parallel_wavegan/utils/utils.py, test/test_hifigan.py
Fixed typo #295 and added workaround to load wrong name config.
=> fix typo in hifigan

setup.py
fix https://github.com/kan-bayashi/ParallelWaveGAN/runs/6646851174?check_suite_focus=true#step:6:294
=> temporary fixed protobuf version
